// Extracted verbatim from app/dashboard/clinical-tools/page.tsx (Orthopedic Tests
// sub-tab) with a stable `slug` field added to each test for use as a
// translateContent cache key. Content is unchanged from the original hardcoded
// arrays -- only the slug field is new.

export interface OrthoTestContent {
  slug: string;
  name: string;
  targets: string;
  procedure: string;
  positive: string;
  accuracy: string;
}

export const KNEE_TESTS: OrthoTestContent[] = [
  { slug: 'knee-lachman-test', name: 'Lachman Test', targets: 'Legamento crociato anteriore (LCA)', procedure: "Paziente supino, ginocchio flesso a 20-30°. L'esaminatore stabilizza il femore con una mano e con l'altra applica una forza anteriore sulla tibia prossimale, valutando l'entità della traslazione anteriore e la qualità dell'arresto finale (end-feel).", positive: "Aumentata traslazione anteriore della tibia rispetto al lato controlaterale, con end-feel molle o assente (non netto e deciso).", accuracy: 'Sensibilità 80-87%, specificità 90-97% — considerato il test clinico singolo più accurato per la diagnosi di lesione del LCA, superiore al cassetto anteriore.' },
  { slug: 'knee-cassetto-anteriore-anterior-drawer-test', name: 'Cassetto Anteriore (Anterior Drawer Test)', targets: 'Legamento crociato anteriore (LCA)', procedure: "Paziente supino, anca flessa a 45°, ginocchio flesso a 90°, piede stabilizzato sul lettino. L'esaminatore afferra la tibia prossimale con entrambe le mani e applica una trazione anteriore.", positive: "Aumentata traslazione anteriore della tibia rispetto al lato controlaterale.", accuracy: "Sensibilità 40-90% (ampia variabilità in letteratura, meno affidabile del Lachman), specificità generalmente >90%. La flessione a 90° può essere limitata dalla guardia muscolare del paziente o dal dolore in fase acuta, riducendone l'accuratezza rispetto al Lachman." },
  { slug: 'knee-cassetto-posteriore-posterior-drawer-test', name: 'Cassetto Posteriore (Posterior Drawer Test)', targets: 'Legamento crociato posteriore (LCP)', procedure: "Stessa posizione del cassetto anteriore, ma la forza applicata dall'esaminatore è diretta posteriormente sulla tibia prossimale.", positive: "Aumentata traslazione posteriore della tibia rispetto al lato controlaterale.", accuracy: 'Considerato il test più accurato per il LCP, con specificità generalmente elevata (>90%); sensibilità variabile in letteratura.' },
  { slug: 'knee-mcmurray-test', name: 'McMurray Test', targets: 'Menischi (mediale e laterale)', procedure: "Paziente supino, ginocchio flesso al massimo. L'esaminatore applica una rotazione tibiale (esterna per il menisco mediale, interna per il laterale) mentre estende gradualmente il ginocchio, palpando la rima articolare.", positive: "Click, schiocco o dolore palpabile/udibile durante la manovra, riproducibile a livello della rima articolare.", accuracy: 'Sensibilità moderata-bassa (35-60% a seconda degli studi), specificità elevata (85-95%) — utile per confermare quando positivo, meno affidabile per escludere una lesione quando negativo.' },
  { slug: 'knee-test-di-thessaly', name: 'Test di Thessaly', targets: 'Menischi (mediale e laterale)', procedure: "Paziente in appoggio monopodalico sull'arto da esaminare con ginocchio flesso a 20°, mano dell'esaminatore di supporto. Il paziente ruota il tronco e il ginocchio internamente ed esternamente mantenendo la flessione.", positive: "Dolore alla rima articolare mediale o laterale, spesso associato a sensazione di blocco articolare.", accuracy: "Sensibilità e specificità elevate in diversi studi (intorno all'85-90% per entrambe), superiore al McMurray in alcune comparazioni dirette, ma richiede la capacità del paziente di reggere il carico monopodalico." },
  { slug: 'knee-valgus-stress-test', name: 'Valgus Stress Test', targets: 'Legamento collaterale mediale (LCM)', procedure: "Paziente supino, ginocchio in leggera flessione (20-30°). L'esaminatore applica una forza in valgo (verso l'interno) alla gamba, stabilizzando la coscia.", positive: "Dolore e/o apertura eccessiva della rima articolare mediale rispetto al lato controlaterale.", accuracy: 'Test clinico consolidato per il LCM; il grado di apertura articolare orienta la severità della lesione (I-III).' },
  { slug: 'knee-varus-stress-test', name: 'Varus Stress Test', targets: 'Legamento collaterale laterale (LCL)', procedure: "Stessa posizione del valgus test, ma la forza applicata è diretta in varo (verso l'esterno).", positive: "Dolore e/o apertura eccessiva della rima articolare laterale rispetto al lato controlaterale.", accuracy: 'Test clinico consolidato per il LCL, meno frequentemente lesionato isolatamente rispetto al LCM.' },
  { slug: 'knee-patellar-apprehension-test', name: "Patellar Apprehension Test", targets: 'Instabilità/lussazione femoro-rotulea', procedure: "Paziente supino, ginocchio in leggera flessione. L'esaminatore applica una pressione laterale sul margine mediale della rotula, spingendola lateralmente.", positive: "Il paziente contrae il quadricipite in risposta o mostra evidente apprensione/resistenza al movimento, per timore di sublussazione.", accuracy: 'Test clinico classico per instabilità rotulea, alta specificità quando la risposta di apprensione è chiara e riproducibile.' },
];

export const SHOULDER_TESTS: OrthoTestContent[] = [
  { slug: 'shoulder-neer-test', name: 'Neer Test', targets: 'Conflitto subacromiale (impingement)', procedure: "Paziente seduto o in piedi. L'esaminatore stabilizza la scapola con una mano e con l'altra solleva passivamente il braccio in flessione, sull'intero range di movimento.", positive: "Comparsa di dolore durante la flessione passiva, tipicamente tra 70° e 120°.", accuracy: 'Sensibilità 79-89%, specificità 53-59% (meta-analisi) — test sensibile, utile soprattutto per escludere il conflitto quando negativo; una positività isolata non è diagnostica.' },
  { slug: 'shoulder-hawkins-kennedy-test', name: 'Hawkins-Kennedy Test', targets: 'Conflitto subacromiale (impingement)', procedure: "Spalla e gomito flessi entrambi a 90°. L'esaminatore ruota internamente passivamente la spalla.", positive: "Comparsa di dolore durante la rotazione interna.", accuracy: 'Sensibilità 63-92%, specificità 25-67% (ampia variabilità in letteratura) — come il Neer, alta sensibilità ma bassa specificità: utile in combinazione con altri test, non da solo.' },
  { slug: 'shoulder-empty-can-test-jobe-test', name: 'Empty Can Test (Jobe Test)', targets: 'Muscolo/tendine sovraspinato', procedure: "Braccio abdotto a 90° nel piano scapolare, ruotato internamente (pollice verso il basso, come svuotando una lattina). L'esaminatore applica una forza verso il basso mentre il paziente resiste.", positive: "Dolore e/o incapacità di mantenere la posizione contro resistenza.", accuracy: 'Sensibilità 50%, specificità 87% — test più specifico che sensibile per patologia del sovraspinato; una positività chiara è clinicamente significativa.' },
  { slug: 'shoulder-speeds-test', name: "Speed's Test", targets: 'Tendine del capo lungo del bicipite', procedure: "Gomito esteso, avambraccio supinato, spalla flessa a circa 90°. L'esaminatore applica una resistenza verso il basso mentre il paziente flette ulteriormente la spalla.", positive: "Dolore localizzato al solco bicipitale anteriore.", accuracy: 'Sensibilità relativamente bassa (circa 32% per lesioni SLAP in meta-analisi), specificità moderata (~61%) — va interpretato insieme al quadro clinico complessivo, non isolatamente.' },
  { slug: 'shoulder-drop-arm-test', name: 'Drop Arm Test', targets: 'Lesione massiva della cuffia dei rotatori (in particolare sovraspinato)', procedure: "Il braccio del paziente viene passivamente abdotto a 90°; viene chiesto di abbassarlo lentamente e controllatamente fino al fianco.", positive: "Il braccio cade bruscamente e in modo incontrollato, o il paziente avverte dolore severo durante la discesa controllata.", accuracy: 'Test ad alta specificità (fino al 97%) ma sensibilità generalmente bassa — quando positivo è fortemente suggestivo di lesione ampia della cuffia dei rotatori.' },
  { slug: 'shoulder-apprehension-test-spalla', name: 'Apprehension Test (spalla)', targets: 'Instabilità gleno-omerale anteriore', procedure: "Paziente supino, spalla abdotta a 90° e gomito flesso a 90°. L'esaminatore ruota progressivamente esternamente la spalla.", positive: "Il paziente mostra apprensione, resistenza o richiede l'interruzione del test per timore di sublussazione/lussazione anteriore, più che dolore puro.", accuracy: "Test clinico classico per instabilità anteriore, alta specificità quando la risposta è di vera apprensione (non solo dolore)." },
  { slug: 'shoulder-relocation-test', name: 'Relocation Test', targets: "Instabilità gleno-omerale anteriore (conferma dell'Apprehension Test)", procedure: "Segue l'Apprehension Test: quando il paziente riporta apprensione, l'esaminatore applica una forza posteriore sulla testa omerale mantenendo la stessa posizione.", positive: "L'apprensione o il dolore si riducono significativamente con la forza posteriore applicata.", accuracy: "Aumenta la specificità diagnostica quando combinato con l'Apprehension Test positivo; la combinazione dei due test è considerata più affidabile del singolo test." },
  { slug: 'shoulder-yergason-test', name: 'Yergason Test', targets: 'Tendine del capo lungo del bicipite / stabilità del solco bicipitale', procedure: "Gomito flesso a 90°, avambraccio pronato. L'esaminatore resiste attivamente alla supinazione dell'avambraccio e alla rotazione esterna della spalla eseguite dal paziente.", positive: "Dolore al solco bicipitale, con o senza sensazione di scatto/instabilità del tendine.", accuracy: "Sensibilità generalmente bassa, specificità elevata (fino all'86%) — utile soprattutto per confermare quando positivo." },
];

export const SPINE_TESTS: OrthoTestContent[] = [
  { slug: 'spine-straight-leg-raise-slr-las-gue', name: 'Straight Leg Raise (SLR / Lasègue)', targets: 'Radicolopatia lombare da ernia del disco (in particolare L4-S1)', procedure: "Paziente supino, arto inferiore in estensione. L'esaminatore solleva passivamente la gamba mantenendo il ginocchio esteso, fino alla comparsa di sintomi o a 70-90° di flessione d'anca.", positive: "Riproduzione del dolore radicolare lungo l'arto (non solo dolore locale lombare o alla coscia posteriore) tra circa 30° e 70° di sollevamento.", accuracy: "Sensibilità elevata in popolazioni chirurgiche (fino al 90%+) ma specificità bassa (10-40%) — test utile soprattutto per escludere un'ernia discale quando negativo, meno affidabile per confermarla da solo." },
  { slug: 'spine-crossed-straight-leg-raise', name: 'Crossed Straight Leg Raise', targets: 'Radicolopatia lombare da ernia del disco', procedure: "Stessa manovra dello SLR, ma eseguita sull'arto controlaterale (asintomatico) rispetto al lato dei sintomi.", positive: "Riproduzione del dolore radicolare sull'arto sintomatico durante il sollevamento dell'arto sano.", accuracy: "Specificità molto elevata (85-90%) ma sensibilità bassa (circa 25-30%) — quando positivo è fortemente suggestivo di compressione radicolare significativa, ma la sua assenza non esclude la patologia." },
  { slug: 'spine-slump-test', name: 'Slump Test', targets: 'Radicolopatia lombare / tensione del sistema nervoso', procedure: "Paziente seduto, viene guidato progressivamente attraverso flessione toracolombare, flessione cervicale, estensione del ginocchio e dorsiflessione della caviglia, aggiungendo tensione neurale a ogni step.", positive: "Riproduzione dei sintomi radicolari familiari al paziente, tipicamente alleviati dall'estensione cervicale (elemento chiave per la diagnosi differenziale da una tensione puramente muscolare posteriore della coscia).", accuracy: 'Sensibilità più elevata dello SLR (circa 80-84% in alcuni studi comparativi), specificità lievemente inferiore allo SLR (circa 83%) — utile in particolare quando lo SLR risulta negativo nonostante un forte sospetto clinico.' },
  { slug: 'spine-test-di-spurling', name: "Test di Spurling", targets: 'Radicolopatia cervicale (non lombare, incluso qui come test classico complementare per la valutazione della colonna)', procedure: "Paziente seduto, collo esteso e inclinato lateralmente verso il lato sintomatico. L'esaminatore applica una lieve compressione assiale sul vertice del capo.", positive: "Riproduzione o esacerbazione del dolore radicolare irradiato all'arto superiore.", accuracy: "Specificità elevata (89-100% secondo diversi studi), sensibilità più bassa e variabile (circa 30-60%) — test utile soprattutto per confermare una compressione radicolare cervicale quando positivo." },
  { slug: 'spine-test-di-schober-modificato', name: "Test di Schober Modificato", targets: 'Mobilità in flessione della colonna lombare', procedure: "Con il paziente in piedi, si marca un punto a livello delle spine iliache postero-superiori (linea di Jacoby) e un secondo punto 10 cm più in alto. Si misura l'aumento della distanza tra i due punti durante la flessione anteriore massima del tronco.", positive: "Non è un test di provocazione ma una misura quantitativa: un aumento inferiore a 5 cm rispetto alla posizione neutra indica una ridotta mobilità in flessione della colonna lombare.", accuracy: "Strumento di misura consolidato e riproducibile per il monitoraggio della mobilità lombare nel tempo (es. spondiloartriti, rigidità post-chirurgica), più che un test diagnostico di provocazione." },
  { slug: 'spine-prone-instability-test', name: "Prone Instability Test", targets: 'Instabilità segmentale lombare', procedure: "Paziente prono sul lettino con il tronco fuori dal bordo e i piedi appoggiati a terra (muscolatura del tronco rilassata). L'esaminatore applica una pressione postero-anteriore sui processi spinosi lombari, prima con i piedi a terra, poi facendo sollevare le gambe al paziente (attivando la muscolatura del tronco).", positive: "Dolore presente nella prima fase (muscolatura rilassata) che si riduce significativamente o scompare nella seconda fase (muscolatura attiva) — suggerisce che la stabilità attiva della muscolatura del tronco compensa un deficit di stabilità passiva.", accuracy: "Fa parte dei criteri clinici comunemente utilizzati per identificare i pazienti che potrebbero beneficiare di un programma di stabilizzazione segmentale lombare, con supporto nella letteratura sulla classificazione del mal di schiena meccanico." },
];

export const HIP_TESTS: OrthoTestContent[] = [
  { slug: 'hip-faber-test-test-di-patrick', name: 'FABER Test (Test di Patrick)', targets: "Patologia intra-articolare dell'anca (conflitto femoro-acetabolare, lesione del labbro), articolazione sacroiliaca, muscolo ileopsoas", procedure: "Paziente supino. La caviglia dell'arto da esaminare viene posizionata sopra il ginocchio controlaterale (posizione a 'figura 4': Flessione, ABduzione, Extrarotazione). L'esaminatore applica una lieve pressione verso il basso sul ginocchio flesso.", positive: "Dolore riprodotto all'inguine (suggestivo di patologia dell'anca), alla regione sacroiliaca posteriore, o incapacità del ginocchio di scendere verso il piano del lettino (limitazione di mobilità).", accuracy: 'Valori molto variabili in letteratura (sensibilità 41-93%, specificità 55-100% a seconda dello studio e della patologia indagata) — test di screening ad ampio spettro, non specifico per una singola struttura; va sempre integrato con altri test per localizzare la fonte del dolore.' },
  { slug: 'hip-fadir-test-impingement-test', name: 'FADIR Test (Impingement Test)', targets: 'Conflitto femoro-acetabolare anteriore (FAI), lesione del labbro acetabolare', procedure: "Paziente supino, anca flessa a 90°. L'esaminatore adduce e ruota internamente passivamente l'anca (Flexion, ADduction, Internal Rotation).", positive: "Riproduzione del dolore inguinale/anteriore familiare al paziente.", accuracy: "Test con la sensibilità più elevata tra i test per lesioni del labbro (fino al 99-100% in alcuni studi), ma specificità generalmente più bassa — un test negativo è quindi molto utile per escludere la patologia, un test positivo va confermato con imaging o test aggiuntivi." },
  { slug: 'hip-thomas-test', name: 'Thomas Test', targets: "Accorciamento/retrazione del muscolo ileopsoas e del retto femorale (flessori dell'anca)", procedure: "Paziente supino sul bordo del lettino. Il paziente porta l'anca controlaterale al petto (appiattendo la lordosi lombare) mentre l'arto da esaminare pende liberamente fuori dal lettino.", positive: "L'arto in esame non riesce a rimanere in completa estensione d'anca con la coscia appoggiata al lettino (indica retrazione dell'ileopsoas); se anche il ginocchio si estende spontaneamente, suggerisce coinvolgimento del retto femorale.", accuracy: "Test clinico consolidato per la valutazione della flessibilità dei flessori d'anca, ampiamente utilizzato nella pratica clinica per orientare il trattamento più che per una diagnosi differenziale strutturale precisa." },
  { slug: 'hip-trendelenburg-test', name: 'Trendelenburg Test', targets: 'Debolezza del medio gluteo / instabilità del bacino sul piano frontale', procedure: "Il paziente sta in appoggio monopodalico su un arto, mentre l'esaminatore osserva la posizione del bacino da dietro.", positive: "Il bacino si abbassa (invece di sollevarsi) sul lato controlaterale all'arto in appoggio, indicando un'insufficienza del medio gluteo dell'arto in carico nel sostenere il bacino.", accuracy: "Test clinico classico e ampiamente utilizzato per la valutazione funzionale della stabilità del bacino, particolarmente rilevante nella riabilitazione post-protesi d'anca e nella valutazione del pattern del cammino." },
  { slug: 'hip-scour-test-quadrant-test', name: 'Scour Test (Quadrant Test)', targets: 'Patologia degenerativa intra-articolare (artrosi, lesioni condrali/labrali)', procedure: "Paziente supino, anca e ginocchio flessi a 90°. L'esaminatore applica una compressione assiale attraverso il femore mentre muove l'anca in un arco di adduzione-abduzione con rotazione.", positive: "Dolore, crepitio o sensazione di blocco durante la manovra.", accuracy: "Test di screening generale per patologia intra-articolare dell'anca, utile in combinazione con altri test più specifici piuttosto che isolatamente." },
  { slug: 'hip-log-roll-test', name: 'Log Roll Test', targets: "Patologia intra-articolare dell'anca (test con elevata specificità per patologia capsulare/articolare)", procedure: "Paziente supino con l'arto in posizione neutra. L'esaminatore ruota passivamente l'intero arto inferiore internamente ed esternamente, facendolo 'rotolare' come un log.", positive: "Dolore riprodotto durante la rotazione, tipicamente localizzato all'inguine.", accuracy: "Test con elevata specificità per patologia intra-articolare (a differenza di molti altri test dell'anca che coinvolgono anche strutture extra-articolari), poiché isola il movimento della sola articolazione coxo-femorale senza stress su muscoli/tendini circostanti." },
];

export const ANKLE_TESTS: OrthoTestContent[] = [
  { slug: 'ankle-anterior-drawer-test-caviglia', name: 'Anterior Drawer Test (caviglia)', targets: 'Legamento peroneo-astragalico anteriore (ATFL)', procedure: "Paziente prono o supino, piede rilassato in leggera flessione plantare. L'esaminatore stabilizza la tibia distale con una mano e con l'altra applica una trazione anteriore sul calcagno/retropiede.", positive: "Traslazione anteriore eccessiva del talo rispetto al lato controlaterale (>1 cm), con end-feel indebolito; talvolta visibile una 'fossetta' cutanea sopra il legamento (suction sign).", accuracy: 'Sensibilità 75-86%, specificità 74-88% a seconda degli studi — accuratezza migliore se eseguito 4-5 giorni dopo il trauma piuttosto che nelle primissime 48 ore.' },
  { slug: 'ankle-talar-tilt-test', name: 'Talar Tilt Test', targets: 'Legamento peroneo-astragalico anteriore e calcaneo-peroneale', procedure: "Paziente supino o prono, caviglia in posizione neutra. L'esaminatore applica una forza in inversione stabilizzando la gamba.", positive: "Eccessiva inclinazione/apertura del talo rispetto al lato controlaterale.", accuracy: "Test complementare all'anterior drawer per la valutazione del complesso legamentoso laterale." },
  { slug: 'ankle-squeeze-test', name: 'Squeeze Test', targets: 'Sindesmosi tibio-peroneale distale (lesione "alta" di caviglia)', procedure: "Paziente supino. L'esaminatore comprime tibia e perone l'una verso l'altro a livello del terzo medio della gamba.", positive: "Dolore riprodotto a livello della sindesmosi distale.", accuracy: "Test con alta specificità per lesione della sindesmosi, condizione che richiede un percorso riabilitativo diverso e più prolungato." },
  { slug: 'ankle-external-rotation-test-kleiger-test', name: 'External Rotation Test (Kleiger Test)', targets: 'Sindesmosi tibio-peroneale distale', procedure: "Paziente seduto con ginocchio flesso a 90°. L'esaminatore stabilizza la gamba e ruota esternamente il piede.", positive: "Dolore riprodotto a livello della sindesmosi anteriore.", accuracy: "Utilizzato in combinazione con lo Squeeze Test per aumentare l'accuratezza diagnostica." },
  { slug: 'ankle-thompson-test-simmonds-thompson', name: 'Thompson Test (Simmonds-Thompson)', targets: "Rottura del tendine d'Achille", procedure: "Paziente prono con i piedi che sporgono dal bordo del lettino. L'esaminatore comprime il polpaccio a metà altezza.", positive: "Assenza di flessione plantare del piede in risposta alla compressione del polpaccio.", accuracy: "Sensibilità 96%, specificità 93% (fino al 100% in alcuni studi) — test molto accurato per la rottura completa; le rotture parziali possono dare risultati normali." },
  { slug: 'ankle-windlass-test', name: 'Windlass Test', targets: 'Fascite plantare', procedure: "Paziente in piedi o seduto con il piede in carico. L'esaminatore estende passivamente l'alluce mantenendo il ginocchio esteso.", positive: "Riproduzione del dolore plantare familiare, tipicamente a livello dell'inserzione calcaneale.", accuracy: 'Test clinico specifico per la fascite plantare (specificità elevata, sensibilità più variabile).' },
];

export const ELBOW_WRIST_TESTS: OrthoTestContent[] = [
  { slug: 'elbow-wrist-cozens-test', name: "Cozen's Test", targets: 'Epicondilite laterale (gomito del tennista)', procedure: "Paziente con gomito flesso, avambraccio pronato, pugno chiuso e polso in leggera estensione. L'esaminatore stabilizza il gomito e resiste all'estensione attiva del polso.", positive: "Dolore improvviso e acuto localizzato all'epicondilo laterale.", accuracy: "Test clinico classico per l'epicondilite laterale, spesso usato in combinazione con Mill's e Maudsley's Test." },
  { slug: 'elbow-wrist-mills-test', name: "Mill's Test", targets: 'Epicondilite laterale (gomito del tennista)', procedure: "Gomito esteso, avambraccio pronato. L'esaminatore palpa l'epicondilo laterale mentre passivamente flette il polso e prona ulteriormente l'avambraccio.", positive: "Dolore riprodotto a livello dell'epicondilo laterale.", accuracy: "Test complementare al Cozen's Test, basato sullo stiramento passivo." },
  { slug: 'elbow-wrist-phalen-test', name: 'Phalen Test', targets: 'Sindrome del tunnel carpale (nervo mediano)', procedure: "Il paziente flette entrambi i polsi a 90° mantenendo il dorso delle mani a contatto, per circa 60 secondi.", positive: "Comparsa o esacerbazione di parestesie nel territorio del nervo mediano.", accuracy: 'Sensibilità mediana intorno al 70%, specificità elevata (80-93%) — generalmente più affidabile del test di Tinel.' },
  { slug: 'elbow-wrist-test-di-tinel-al-polso', name: "Test di Tinel (al polso)", targets: 'Sindrome del tunnel carpale (nervo mediano)', procedure: "L'esaminatore percuote leggermente e ripetutamente sopra il decorso del nervo mediano a livello del tunnel carpale.", positive: "Sensazione di formicolio/scossa elettrica irradiata nel territorio del nervo mediano.", accuracy: "Sensibilità bassa e variabile (23-67%), specificità elevata (95-99%) — un test positivo è clinicamente significativo, un negativo non esclude la sindrome." },
  { slug: 'elbow-wrist-finkelstein-test', name: 'Finkelstein Test', targets: "Tenosinovite di De Quervain", procedure: "Il paziente flette il pollice all'interno del palmo, chiudendo le altre dita a pugno. L'esaminatore devia passivamente il polso verso il lato ulnare.", positive: "Dolore acuto localizzato al processo stiloideo radiale.", accuracy: "Test clinico classico per la tenosinovite di De Quervain, alta specificità quando il dolore è ben localizzato." },
  { slug: 'elbow-wrist-ligamentous-instability-test-valgus-varus-stress-al-gomito', name: 'Ligamentous Instability Test (Valgus/Varus Stress al gomito)', targets: 'Legamento collaterale ulnare (valgo) e radiale (varo) del gomito', procedure: "Gomito in leggera flessione (20-30°). L'esaminatore applica una forza in valgo o in varo.", positive: "Dolore e/o apertura eccessiva dell'interlinea articolare rispetto al lato controlaterale.", accuracy: "Test clinico consolidato per la stabilità legamentosa del gomito, rilevante negli atleti overhead." },
];

export const CERVICAL_TESTS: OrthoTestContent[] = [
  { slug: 'cervical-spurling-test', name: 'Spurling Test', targets: 'Radicolopatia cervicale', procedure: "Paziente seduto, collo esteso e inclinato lateralmente verso il lato sintomatico. L'esaminatore applica una lieve compressione assiale sul vertice del capo.", positive: "Riproduzione o esacerbazione del dolore radicolare irradiato all'arto superiore.", accuracy: "Specificità elevata (89-100%), sensibilità più bassa e variabile (circa 30-60%) — tra i test più specifici del cluster." },
  { slug: 'cervical-cervical-distraction-test', name: 'Cervical Distraction Test', targets: 'Radicolopatia cervicale', procedure: "Paziente supino. L'esaminatore posiziona una mano sotto il mento e l'altra intorno all'occipite, applicando gradualmente una trazione assiale fino a circa 10-15 kg.", positive: "Riduzione o scomparsa del dolore radicolare durante la trazione.", accuracy: 'Sensibilità 44%, specificità 90-97% — test ad alta specificità, fa parte del cluster diagnostico di Wainner.' },
  { slug: 'cervical-upper-limb-tension-test-a-ultt-a', name: 'Upper Limb Tension Test A (ULTT A)', targets: 'Tensione del sistema nervoso periferico (nervo mediano), radicolopatia cervicale', procedure: "Paziente supino. L'esaminatore posiziona sequenzialmente l'arto superiore in depressione scapolare, abduzione della spalla, supinazione dell'avambraccio con estensione di polso e dita, extrarotazione della spalla, estensione del gomito, infine flessione laterale cervicale.", positive: "Riproduzione dei sintomi familiari, che si modificano con la flessione laterale cervicale.", accuracy: "Alta sensibilità ma bassa specificità — un test negativo è utile per escludere una componente di tensione neurale." },
  { slug: 'cervical-cervical-compression-test', name: 'Cervical Compression Test', targets: 'Radicolopatia cervicale (complementare al distraction test)', procedure: "Paziente seduto in posizione neutra. L'esaminatore applica una compressione assiale delicata sul vertice del capo.", positive: "Riproduzione del dolore radicolare irradiato all'arto superiore.", accuracy: 'Testa le stesse strutture del distraction test ma con meccanismo opposto; la combinazione dei due rafforza il sospetto diagnostico.' },
  { slug: 'cervical-test-di-rotazione-cervicale-attiva', name: 'Test di Rotazione Cervicale Attiva', targets: 'Mobilità cervicale, elemento del cluster diagnostico per radicolopatia', procedure: "Il paziente esegue una rotazione cervicale attiva bilaterale, mentre l'esaminatore misura l'ampiezza del movimento verso il lato sintomatico.", positive: "Rotazione limitata a meno di 60° verso il lato sintomatico.", accuracy: "Elemento del cluster diagnostico di Wainner: insieme a Spurling, distraction test e ULTT positivi, aumenta sostanzialmente la probabilità di radicolopatia." },
  { slug: 'cervical-test-di-estensione-rotazione', name: 'Test di Estensione-Rotazione', targets: 'Patologia delle faccette articolari cervicali', procedure: "Paziente supino. L'esaminatore esegue passivamente un movimento combinato di estensione e rotazione omolaterale del collo.", positive: "Riproduzione del dolore cervicale locale (non irradiato).", accuracy: "Test utile per la diagnosi differenziale tra dolore cervicale meccanico/facettale e vera radicolopatia." },
];
